"""create initial service schema

Revision ID: 2b58c77800bf
Revises:
Create Date: 2026-07-11 10:19:26.556181
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b58c77800bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('input_value', sa.Text(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('request_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_jobs_status_created_at', 'analysis_jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_analysis_jobs_video_created_at', 'analysis_jobs', ['youtube_video_id', 'created_at'], unique=False)
    op.create_table('channels',
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('custom_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('youtube_channel_id')
    )
    op.create_table('secret_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('secret_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_key', 'provider', name='uq_secret_references_key_provider')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('example_vector_collection', sa.String(length=128), nullable=False),
    sa.Column('definition_vector_collection', sa.String(length=128), nullable=False),
    sa.Column('definition_corpus_version', sa.String(length=128), nullable=True),
    sa.Column('retriever_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_job_id'), 'analysis_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_youtube_video_id'), 'analysis_runs', ['youtube_video_id'], unique=False)
    op.create_table('api_quota_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('quota_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_quota_events_job_id'), 'api_quota_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_api_quota_events_provider'), 'api_quota_events', ['provider'], unique=False)
    op.create_index(op.f('ix_api_quota_events_status'), 'api_quota_events', ['status'], unique=False)
    op.create_table('comment_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('youtube_comment_id', sa.String(length=128), nullable=False),
    sa.Column('parent_youtube_comment_id', sa.String(length=128), nullable=True),
    sa.Column('parent_comment_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('reply_depth', sa.Integer(), nullable=False),
    sa.Column('author_display_name', sa.Text(), nullable=True),
    sa.Column('author_channel_id', sa.String(length=128), nullable=True),
    sa.Column('text_display', sa.Text(), nullable=True),
    sa.Column('text_original', sa.Text(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('reply_count', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_snapshot_id'], ['comment_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'youtube_comment_id', name='uq_comments_job_youtube_id')
    )
    op.create_index(op.f('ix_comment_snapshots_author_channel_id'), 'comment_snapshots', ['author_channel_id'], unique=False)
    op.create_index(op.f('ix_comment_snapshots_job_id'), 'comment_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_comment_snapshots_youtube_video_id'), 'comment_snapshots', ['youtube_video_id'], unique=False)
    op.create_index('ix_comments_job_parent', 'comment_snapshots', ['job_id', 'parent_youtube_comment_id'], unique=False)
    op.create_index('ix_comments_job_reply', 'comment_snapshots', ['job_id', 'is_reply'], unique=False)
    op.create_table('job_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'step_key', name='uq_job_steps_job_step')
    )
    op.create_index(op.f('ix_job_steps_job_id'), 'job_steps', ['job_id'], unique=False)
    op.create_index('ix_job_steps_status_started_at', 'job_steps', ['status', 'started_at'], unique=False)
    op.create_table('transcript_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_snapshots_job_id'), 'transcript_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_transcript_snapshots_youtube_video_id'), 'transcript_snapshots', ['youtube_video_id'], unique=False)
    op.create_table('video_metadata_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('channel_title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('made_for_kids', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_metadata_snapshots_job_id'), 'video_metadata_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_video_metadata_snapshots_youtube_channel_id'), 'video_metadata_snapshots', ['youtube_channel_id'], unique=False)
    op.create_index('ix_video_metadata_video_collected', 'video_metadata_snapshots', ['youtube_video_id', 'collected_at'], unique=False)
    op.create_table('comment_analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('comment_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_hate_speech', sa.Boolean(), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=True),
    sa.Column('target_group', sa.Text(), nullable=True),
    sa.Column('hate_type', sa.String(length=64), nullable=True),
    sa.Column('evidence_strength', sa.Numeric(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('similar_cases_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('definition_docs_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rag_context_status', sa.String(length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_snapshot_id'], ['comment_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'comment_snapshot_id', name='uq_comment_results_run_comment')
    )
    op.create_index(op.f('ix_comment_analysis_results_analysis_run_id'), 'comment_analysis_results', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_comment_analysis_results_comment_snapshot_id'), 'comment_analysis_results', ['comment_snapshot_id'], unique=False)
    op.create_table('comment_networks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('graph_type', sa.String(length=64), nullable=False),
    sa.Column('directed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('layout_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_networks_analysis_run_id'), 'comment_networks', ['analysis_run_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('job_step_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['job_step_id'], ['job_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_event_type'), 'operation_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_job_id'), 'operation_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_level'), 'operation_logs', ['level'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_uri', sa.Text(), nullable=True),
    sa.Column('html_uri', sa.Text(), nullable=True),
    sa.Column('source_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('failure_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_analysis_run_id'), 'report_snapshots', ['analysis_run_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcript_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Numeric(), nullable=True),
    sa.Column('end_seconds', sa.Numeric(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_snapshot_id'], ['transcript_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_snapshot_id', 'segment_index', name='uq_segments_snapshot_index')
    )
    op.create_index(op.f('ix_transcript_segments_transcript_snapshot_id'), 'transcript_segments', ['transcript_snapshot_id'], unique=False)
    op.create_table('comment_network_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_key', sa.String(length=160), nullable=False),
    sa.Column('target_node_key', sa.String(length=160), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('comment_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('parent_comment_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('is_hate_speech', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['comment_snapshot_id'], ['comment_snapshots.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['comment_networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_snapshot_id'], ['comment_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_network_edges_network_id'), 'comment_network_edges', ['network_id'], unique=False)
    op.create_index(op.f('ix_comment_network_edges_source_node_key'), 'comment_network_edges', ['source_node_key'], unique=False)
    op.create_index(op.f('ix_comment_network_edges_target_node_key'), 'comment_network_edges', ['target_node_key'], unique=False)
    op.create_table('comment_network_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=160), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('author_channel_id', sa.String(length=128), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('hate_speech_count', sa.Integer(), nullable=False),
    sa.Column('hate_speech_ratio', sa.Numeric(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['comment_networks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'node_key', name='uq_network_nodes_key')
    )
    op.create_index(op.f('ix_comment_network_nodes_author_channel_id'), 'comment_network_nodes', ['author_channel_id'], unique=False)
    op.create_index(op.f('ix_comment_network_nodes_network_id'), 'comment_network_nodes', ['network_id'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_snapshot_id'], ['report_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_report_snapshot_id'), 'report_exports', ['report_snapshot_id'], unique=False)
    op.create_table('script_analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_segment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_hate_speech', sa.Boolean(), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=True),
    sa.Column('target_group', sa.Text(), nullable=True),
    sa.Column('hate_type', sa.String(length=64), nullable=True),
    sa.Column('evidence_strength', sa.Numeric(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('similar_cases_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('definition_docs_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rag_context_status', sa.String(length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'transcript_segment_id', name='uq_script_results_run_segment')
    )
    op.create_index(op.f('ix_script_analysis_results_analysis_run_id'), 'script_analysis_results', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_script_analysis_results_transcript_segment_id'), 'script_analysis_results', ['transcript_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_analysis_results_transcript_segment_id'), table_name='script_analysis_results')
    op.drop_index(op.f('ix_script_analysis_results_analysis_run_id'), table_name='script_analysis_results')
    op.drop_table('script_analysis_results')
    op.drop_index(op.f('ix_report_exports_report_snapshot_id'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_comment_network_nodes_network_id'), table_name='comment_network_nodes')
    op.drop_index(op.f('ix_comment_network_nodes_author_channel_id'), table_name='comment_network_nodes')
    op.drop_table('comment_network_nodes')
    op.drop_index(op.f('ix_comment_network_edges_target_node_key'), table_name='comment_network_edges')
    op.drop_index(op.f('ix_comment_network_edges_source_node_key'), table_name='comment_network_edges')
    op.drop_index(op.f('ix_comment_network_edges_network_id'), table_name='comment_network_edges')
    op.drop_table('comment_network_edges')
    op.drop_index(op.f('ix_transcript_segments_transcript_snapshot_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_report_snapshots_analysis_run_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_operation_logs_level'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_job_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_event_type'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_comment_networks_analysis_run_id'), table_name='comment_networks')
    op.drop_table('comment_networks')
    op.drop_index(op.f('ix_comment_analysis_results_comment_snapshot_id'), table_name='comment_analysis_results')
    op.drop_index(op.f('ix_comment_analysis_results_analysis_run_id'), table_name='comment_analysis_results')
    op.drop_table('comment_analysis_results')
    op.drop_index('ix_video_metadata_video_collected', table_name='video_metadata_snapshots')
    op.drop_index(op.f('ix_video_metadata_snapshots_youtube_channel_id'), table_name='video_metadata_snapshots')
    op.drop_index(op.f('ix_video_metadata_snapshots_job_id'), table_name='video_metadata_snapshots')
    op.drop_table('video_metadata_snapshots')
    op.drop_index(op.f('ix_transcript_snapshots_youtube_video_id'), table_name='transcript_snapshots')
    op.drop_index(op.f('ix_transcript_snapshots_job_id'), table_name='transcript_snapshots')
    op.drop_table('transcript_snapshots')
    op.drop_index('ix_job_steps_status_started_at', table_name='job_steps')
    op.drop_index(op.f('ix_job_steps_job_id'), table_name='job_steps')
    op.drop_table('job_steps')
    op.drop_index('ix_comments_job_reply', table_name='comment_snapshots')
    op.drop_index('ix_comments_job_parent', table_name='comment_snapshots')
    op.drop_index(op.f('ix_comment_snapshots_youtube_video_id'), table_name='comment_snapshots')
    op.drop_index(op.f('ix_comment_snapshots_job_id'), table_name='comment_snapshots')
    op.drop_index(op.f('ix_comment_snapshots_author_channel_id'), table_name='comment_snapshots')
    op.drop_table('comment_snapshots')
    op.drop_index(op.f('ix_api_quota_events_status'), table_name='api_quota_events')
    op.drop_index(op.f('ix_api_quota_events_provider'), table_name='api_quota_events')
    op.drop_index(op.f('ix_api_quota_events_job_id'), table_name='api_quota_events')
    op.drop_table('api_quota_events')
    op.drop_index(op.f('ix_analysis_runs_youtube_video_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_job_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('secret_references')
    op.drop_table('channels')
    op.drop_index('ix_analysis_jobs_video_created_at', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_status_created_at', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
